// ---------- Localization ----------
// 15 languages: English, Turkish, Azerbaijani, Georgian, Spanish, French,
// German, Italian, Portuguese, Russian, Arabic, Chinese, Hindi, Japanese, Korean.

const LANGUAGES = [
  { code: "en", name: "English" },
  { code: "tr", name: "Türkçe" },
  { code: "az", name: "Azərbaycanca" },
  { code: "ka", name: "ქართული" },
  { code: "es", name: "Español" },
  { code: "fr", name: "Français" },
  { code: "de", name: "Deutsch" },
  { code: "it", name: "Italiano" },
  { code: "pt", name: "Português" },
  { code: "ru", name: "Русский" },
  { code: "ar", name: "العربية" },
  { code: "zh", name: "中文" },
  { code: "hi", name: "हिन्दी" },
  { code: "ja", name: "日本語" },
  { code: "ko", name: "한국어" },
];

const I18N_KEYS = {
  nav_home: { en: "Home", tr: "Ana Sayfa", az: "Ana Səhifə", ka: "მთავარი", es: "Inicio", fr: "Accueil", de: "Start", it: "Home", pt: "Início", ru: "Главная", ar: "الرئيسية", zh: "首页", hi: "होम", ja: "ホーム", ko: "홈" },
  nav_challenge: { en: "Daily", tr: "Görev", az: "Tapşırıq", ka: "დავალება", es: "Reto", fr: "Défi", de: "Täglich", it: "Sfida", pt: "Desafio", ru: "Задание", ar: "التحدي", zh: "每日挑战", hi: "चैलेंज", ja: "デイリー", ko: "데일리" },
  nav_levels: { en: "Levels", tr: "Seviyeler", az: "Səviyyələr", ka: "დონეები", es: "Niveles", fr: "Niveaux", de: "Level", it: "Livelli", pt: "Níveis", ru: "Уровни", ar: "المستويات", zh: "关卡", hi: "लेवल", ja: "レベル", ko: "레벨" },
  nav_settings: { en: "Settings", tr: "Ayarlar", az: "Ayarlar", ka: "პარამეტრები", es: "Ajustes", fr: "Réglages", de: "Einstellungen", it: "Impostazioni", pt: "Configurações", ru: "Настройки", ar: "الإعدادات", zh: "设置", hi: "सेटिंग्स", ja: "設定", ko: "설정" },
  level_label: { en: "Level {n}", tr: "Seviye {n}", az: "Səviyyə {n}", ka: "დონე {n}", es: "Nivel {n}", fr: "Niveau {n}", de: "Level {n}", it: "Livello {n}", pt: "Nível {n}", ru: "Уровень {n}", ar: "المستوى {n}", zh: "第 {n} 关", hi: "लेवल {n}", ja: "レベル {n}", ko: "레벨 {n}" },
  play: { en: "Play", tr: "Oyna", az: "Oyna", ka: "თამაში", es: "Jugar", fr: "Jouer", de: "Spielen", it: "Gioca", pt: "Jogar", ru: "Играть", ar: "ابدأ اللعب", zh: "开始游戏", hi: "खेलें", ja: "プレイ", ko: "플레이" },
  daily_challenge: { en: "Daily Challenge", tr: "Günlük Görev", az: "Günlük Tapşırıq", ka: "დღის დავალება", es: "Reto Diario", fr: "Défi du Jour", de: "Tägliche Herausforderung", it: "Sfida Giornaliera", pt: "Desafio Diário", ru: "Ежедневное Задание", ar: "التحدي اليومي", zh: "每日挑战", hi: "दैनिक चैलेंज", ja: "デイリーチャレンジ", ko: "데일리 챌린지" },
  daily_status_default: { en: "Solve today's special challenge and test your speed!", tr: "Bugünün özel görevini çöz ve hızını ölç!", az: "Bu günün xüsusi tapşırığını həll et və sürətini sına!", ka: "გადაჭერი დღევანდელი სპეციალური დავალება და გამოსცადე სიჩქარე!", es: "¡Resuelve el reto especial de hoy y pon a prueba tu velocidad!", fr: "Résous le défi spécial du jour et teste ta rapidité !", de: "Löse die heutige Herausforderung und teste deine Geschwindigkeit!", it: "Risolvi la sfida speciale di oggi e metti alla prova la tua velocità!", pt: "Resolva o desafio especial de hoje e teste sua velocidade!", ru: "Реши сегодняшнее особое задание и проверь свою скорость!", ar: "حل تحدي اليوم الخاص واختبر سرعتك!", zh: "完成今天的特别挑战，测试你的速度！", hi: "आज की खास चुनौती हल करें और अपनी स्पीड परखें!", ja: "今日の特別チャレンジを解いてスピードを試そう！", ko: "오늘의 특별 챌린지를 풀고 속도를 테스트해보세요!" },
  daily_start: { en: "Start Daily Challenge", tr: "Günlük Göreve Başla", az: "Günlük Tapşırığa Başla", ka: "დაიწყე დღის დავალება", es: "Comenzar Reto Diario", fr: "Commencer le Défi du Jour", de: "Tägliche Herausforderung Starten", it: "Inizia la Sfida Giornaliera", pt: "Iniciar Desafio Diário", ru: "Начать Ежедневное Задание", ar: "ابدأ التحدي اليومي", zh: "开始每日挑战", hi: "दैनिक चैलेंज शुरू करें", ja: "デイリーチャレンジを始める", ko: "데일리 챌린지 시작" },
  daily_play_again: { en: "Play Again", tr: "Tekrar Oyna", az: "Yenidən Oyna", ka: "თავიდან თამაში", es: "Jugar de Nuevo", fr: "Rejouer", de: "Erneut Spielen", it: "Gioca Ancora", pt: "Jogar Novamente", ru: "Играть Снова", ar: "العب مرة أخرى", zh: "再玩一次", hi: "फिर से खेलें", ja: "もう一度プレイ", ko: "다시 플레이" },
  daily_best_status: { en: "Today's best: {score} pts • {time}", tr: "Bugünkü en iyi skorun: {score} puan • {time}", az: "Bu günkü ən yaxşı nəticən: {score} xal • {time}", ka: "დღევანდელი საუკეთესო შედეგი: {score} ქულა • {time}", es: "Tu mejor puntuación de hoy: {score} pts • {time}", fr: "Ton meilleur score aujourd'hui : {score} pts • {time}", de: "Deine heutige Bestpunktzahl: {score} Pkt • {time}", it: "Il tuo miglior punteggio di oggi: {score} pt • {time}", pt: "Sua melhor pontuação hoje: {score} pts • {time}", ru: "Лучший результат сегодня: {score} очк. • {time}", ar: "أفضل نتيجة لك اليوم: {score} نقطة • {time}", zh: "今日最佳成绩：{score} 分 • {time}", hi: "आज का सबसे अच्छा स्कोर: {score} अंक • {time}", ja: "今日のベストスコア：{score}点 • {time}", ko: "오늘의 최고 점수: {score}점 • {time}" },
  new_challenge_in: { en: "New challenge: {time}", tr: "Yeni görev: {time}", az: "Yeni tapşırıq: {time}", ka: "ახალი დავალება: {time}", es: "Nuevo reto: {time}", fr: "Nouveau défi : {time}", de: "Neue Herausforderung: {time}", it: "Nuova sfida: {time}", pt: "Novo desafio: {time}", ru: "Новое задание: {time}", ar: "تحدٍ جديد: {time}", zh: "新挑战：{time}", hi: "नया चैलेंज: {time}", ja: "次のチャレンジ: {time}", ko: "새 챌린지: {time}" },
  new_challenge_in_suffix: { en: "New challenge in {time}", tr: "Yeni görev {time} sonra", az: "Yeni tapşırıq {time} sonra", ka: "ახალი დავალება {time}-ში", es: "Nuevo reto en {time}", fr: "Nouveau défi dans {time}", de: "Neue Herausforderung in {time}", it: "Nuova sfida tra {time}", pt: "Novo desafio em {time}", ru: "Новое задание через {time}", ar: "تحدٍ جديد بعد {time}", zh: "{time} 后开启新挑战", hi: "{time} में नया चैलेंज", ja: "{time}後に新しいチャレンジ", ko: "{time} 후 새 챌린지" },
  leaderboard_title: { en: "🏆 Today's Ranking", tr: "🏆 Bugünün Sıralaması", az: "🏆 Bu Günün Sıralaması", ka: "🏆 დღევანდელი რეიტინგი", es: "🏆 Ranking de Hoy", fr: "🏆 Classement du Jour", de: "🏆 Heutige Rangliste", it: "🏆 Classifica di Oggi", pt: "🏆 Ranking de Hoje", ru: "🏆 Рейтинг Дня", ar: "🏆 ترتيب اليوم", zh: "🏆 今日排行榜", hi: "🏆 आज की रैंकिंग", ja: "🏆 本日のランキング", ko: "🏆 오늘의 순위" },
  player_default: { en: "Player", tr: "Oyuncu", az: "Oyunçu", ka: "მოთამაშე", es: "Jugador", fr: "Joueur", de: "Spieler", it: "Giocatore", pt: "Jogador", ru: "Игрок", ar: "اللاعب", zh: "玩家", hi: "खिलाड़ी", ja: "プレイヤー", ko: "플레이어" },
  choose_name: { en: "Choose a name", tr: "Adını seç", az: "Adını seç", ka: "აირჩიე სახელი", es: "Elige un nombre", fr: "Choisis un nom", de: "Namen wählen", it: "Scegli un nome", pt: "Escolha um nome", ru: "Выбери имя", ar: "اختر اسمًا", zh: "选择昵称", hi: "नाम चुनें", ja: "名前を選択", ko: "이름 선택" },
  leaderboard_empty: { en: "No scores yet. Be the first!", tr: "Henüz sıralama yok. İlk skoru sen koy!", az: "Hələ sıralama yoxdur. İlk nəticəni sən qoy!", ka: "რეიტინგი ჯერ ცარიელია. იყავი პირველი!", es: "Aún no hay puntuaciones. ¡Sé el primero!", fr: "Pas encore de scores. Sois le premier !", de: "Noch keine Einträge. Sei der Erste!", it: "Ancora nessun punteggio. Sii il primo!", pt: "Ainda sem pontuações. Seja o primeiro!", ru: "Пока нет результатов. Будь первым!", ar: "لا توجد نتائج بعد. كن الأول!", zh: "暂无排名，快来抢第一！", hi: "अभी कोई स्कोर नहीं है। सबसे पहले बनें!", ja: "まだスコアがありません。一番乗りになろう！", ko: "아직 점수가 없습니다. 첫 번째가 되어보세요!" },
  leaderboard_load_error: { en: "Couldn't load the ranking. Check your connection.", tr: "Sıralama yüklenemedi. Bağlantını kontrol et.", az: "Sıralama yüklənmədi. Bağlantını yoxla.", ka: "რეიტინგის ჩატვირთვა ვერ მოხერხდა. შეამოწმე კავშირი.", es: "No se pudo cargar el ranking. Revisa tu conexión.", fr: "Impossible de charger le classement. Vérifie ta connexion.", de: "Rangliste konnte nicht geladen werden. Prüfe deine Verbindung.", it: "Impossibile caricare la classifica. Controlla la connessione.", pt: "Não foi possível carregar o ranking. Verifique sua conexão.", ru: "Не удалось загрузить рейтинг. Проверь подключение.", ar: "تعذر تحميل الترتيب. تحقق من اتصالك.", zh: "无法加载排行榜，请检查网络连接。", hi: "रैंकिंग लोड नहीं हो सकी। अपना कनेक्शन जांचें।", ja: "ランキングを読み込めませんでした。接続を確認してください。", ko: "순위를 불러올 수 없습니다. 연결을 확인하세요." },
  levels: { en: "Levels", tr: "Seviyeler", az: "Səviyyələr", ka: "დონეები", es: "Niveles", fr: "Niveaux", de: "Level", it: "Livelli", pt: "Níveis", ru: "Уровни", ar: "المستويات", zh: "关卡", hi: "लेवल", ja: "レベル", ko: "레벨" },
  achievements: { en: "Achievements", tr: "Başarımlar", az: "Nailiyyətlər", ka: "მიღწევები", es: "Logros", fr: "Succès", de: "Erfolge", it: "Obiettivi", pt: "Conquistas", ru: "Достижения", ar: "الإنجازات", zh: "成就", hi: "अचीवमेंट्स", ja: "実績", ko: "업적" },
  settings_title: { en: "Settings", tr: "Ayarlar", az: "Ayarlar", ka: "პარამეტრები", es: "Ajustes", fr: "Réglages", de: "Einstellungen", it: "Impostazioni", pt: "Configurações", ru: "Настройки", ar: "الإعدادات", zh: "设置", hi: "सेटिंग्स", ja: "設定", ko: "설정" },
  sound: { en: "Sound", tr: "Ses", az: "Səs", ka: "ხმა", es: "Sonido", fr: "Son", de: "Ton", it: "Suono", pt: "Som", ru: "Звук", ar: "الصوت", zh: "声音", hi: "साउंड", ja: "サウンド", ko: "소리" },
  vibration: { en: "Vibration", tr: "Titreşim", az: "Vibrasiya", ka: "ვიბრაცია", es: "Vibración", fr: "Vibration", de: "Vibration", it: "Vibrazione", pt: "Vibração", ru: "Вибрация", ar: "الاهتزاز", zh: "震动", hi: "वाइब्रेशन", ja: "バイブレーション", ko: "진동" },
  dark_mode: { en: "Dark Mode", tr: "Karanlık Mod", az: "Qaranlıq Rejim", ka: "მუქი რეჟიმი", es: "Modo Oscuro", fr: "Mode Sombre", de: "Dunkler Modus", it: "Modalità Scura", pt: "Modo Escuro", ru: "Тёмная Тема", ar: "الوضع الداكن", zh: "深色模式", hi: "डार्क मोड", ja: "ダークモード", ko: "다크 모드" },
  colored_arrows: { en: "Colored Arrows", tr: "Renkli Oklar", az: "Rəngli Oxlar", ka: "ფერადი ისრები", es: "Flechas de Colores", fr: "Flèches Colorées", de: "Farbige Pfeile", it: "Frecce Colorate", pt: "Setas Coloridas", ru: "Цветные Стрелки", ar: "أسهم ملونة", zh: "彩色箭头", hi: "रंगीन एरो", ja: "カラー矢印", ko: "컬러 화살표" },
  how_to_play: { en: "How to Play", tr: "Nasıl Oynanır", az: "Necə Oynanır", ka: "როგორ ვითამაშოთ", es: "Cómo Jugar", fr: "Comment Jouer", de: "Spielanleitung", it: "Come Giocare", pt: "Como Jogar", ru: "Как Играть", ar: "كيفية اللعب", zh: "玩法说明", hi: "कैसे खेलें", ja: "遊び方", ko: "게임 방법" },
  reset_progress: { en: "Reset Progress", tr: "İlerlemeyi Sıfırla", az: "İrəliləyişi Sıfırla", ka: "პროგრესის გადაყენება", es: "Restablecer Progreso", fr: "Réinitialiser la Progression", de: "Fortschritt Zurücksetzen", it: "Reimposta Progressi", pt: "Redefinir Progresso", ru: "Сбросить Прогресс", ar: "إعادة ضبط التقدم", zh: "重置进度", hi: "प्रोग्रेस रीसेट करें", ja: "進行状況をリセット", ko: "진행 상황 초기화" },
  reset_confirm: { en: "All your level progress will be reset. Are you sure?", tr: "Tüm seviye ilerlemen sıfırlanacak. Emin misin?", az: "Bütün səviyyə irəliləyişin sıfırlanacaq. Əminsən?", ka: "ყველა დონის პროგრესი გადაყენდება. დარწმუნებული ხარ?", es: "Se reiniciará todo el progreso de niveles. ¿Estás seguro?", fr: "Toute ta progression sera réinitialisée. Es-tu sûr ?", de: "Dein gesamter Levelfortschritt wird zurückgesetzt. Bist du sicher?", it: "Tutti i progressi nei livelli verranno azzerati. Sei sicuro?", pt: "Todo o seu progresso nos níveis será redefinido. Tem certeza?", ru: "Весь прогресс по уровням будет сброшен. Ты уверен?", ar: "سيتم إعادة ضبط كل تقدمك في المستويات. هل أنت متأكد؟", zh: "所有关卡进度将被重置，确定吗？", hi: "आपकी सारी लेवल प्रोग्रेस रीसेट हो जाएगी। पक्का?", ja: "すべてのレベル進行状況がリセットされます。よろしいですか？", ko: "모든 레벨 진행 상황이 초기화됩니다. 계속하시겠습니까?" },
  undo: { en: "Undo", tr: "Geri Al", az: "Geri Al", ka: "გაუქმება", es: "Deshacer", fr: "Annuler", de: "Rückgängig", it: "Annulla", pt: "Desfazer", ru: "Отменить", ar: "تراجع", zh: "撤销", hi: "अनडू", ja: "元に戻す", ko: "되돌리기" },
  hint: { en: "Hint", tr: "İpucu", az: "İpucu", ka: "მინიშნება", es: "Pista", fr: "Indice", de: "Hinweis", it: "Suggerimento", pt: "Dica", ru: "Подсказка", ar: "تلميح", zh: "提示", hi: "हिंट", ja: "ヒント", ko: "힌트" },
  level_complete: { en: "Level Complete!", tr: "Seviye Tamamlandı!", az: "Səviyyə Tamamlandı!", ka: "დონე დასრულდა!", es: "¡Nivel Completado!", fr: "Niveau Terminé !", de: "Level Geschafft!", it: "Livello Completato!", pt: "Nível Concluído!", ru: "Уровень Пройден!", ar: "اكتمل المستوى!", zh: "关卡完成！", hi: "लेवल पूरा हुआ!", ja: "レベルクリア！", ko: "레벨 완료!" },
  escaped_level: { en: "You escaped level {n}.", tr: "{n}. seviyeden kaçtın.", az: "{n}-ci səviyyədən qaçdın.", ka: "გამოვედი {n}-ე დონიდან.", es: "Escapaste del nivel {n}.", fr: "Tu t'es échappé du niveau {n}.", de: "Du bist aus Level {n} entkommen.", it: "Sei scappato dal livello {n}.", pt: "Você escapou do nível {n}.", ru: "Ты выбрался с уровня {n}.", ar: "هربت من المستوى {n}.", zh: "你已逃出第 {n} 关。", hi: "आप लेवल {n} से बाहर निकल गए।", ja: "レベル{n}を脱出しました。", ko: "레벨 {n}에서 탈출했습니다." },
  moves_suffix: { en: "{n} moves", tr: "{n} hamle", az: "{n} hərəkət", ka: "{n} სვლა", es: "{n} movimientos", fr: "{n} coups", de: "{n} Züge", it: "{n} mosse", pt: "{n} jogadas", ru: "{n} ходов", ar: "{n} حركة", zh: "{n} 步", hi: "{n} चालें", ja: "{n}手", ko: "{n}수" },
  continue: { en: "Continue", tr: "Devam", az: "Davam", ka: "შემდეგი", es: "Continuar", fr: "Continuer", de: "Weiter", it: "Continua", pt: "Continuar", ru: "Далее", ar: "متابعة", zh: "继续", hi: "जारी रखें", ja: "次へ", ko: "계속" },
  start: { en: "Start", tr: "Başla", az: "Başla", ka: "დაწყება", es: "Empezar", fr: "Commencer", de: "Start", it: "Inizia", pt: "Começar", ru: "Начать", ar: "ابدأ", zh: "开始", hi: "शुरू करें", ja: "スタート", ko: "시작" },
  ok: { en: "OK", tr: "Tamam", az: "Oldu", ka: "კარგი", es: "Vale", fr: "OK", de: "OK", it: "OK", pt: "OK", ru: "ОК", ar: "حسنًا", zh: "好的", hi: "ठीक है", ja: "OK", ko: "확인" },
  hearts_gone: { en: "Out of Hearts", tr: "Canların Bitti", az: "Canların Bitdi", ka: "გული დაგეთავდა", es: "Sin Corazones", fr: "Plus de Cœurs", de: "Keine Leben Mehr", it: "Vite Finite", pt: "Sem Vidas", ru: "Жизни Закончились", ar: "نفذت القلوب", zh: "生命用尽", hi: "जान खत्म", ja: "ハートがなくなりました", ko: "하트가 모두 사라졌습니다" },
  breathe_retry: { en: "Take a breath and try again.", tr: "Bir nefes al ve tekrar dene.", az: "Bir nəfəs al və yenidən cəhd et.", ka: "ჩაისუნთქე და კიდევ ერთხელ სცადე.", es: "Respira hondo e inténtalo de nuevo.", fr: "Respire un peu et réessaie.", de: "Atme tief durch und versuch's noch einmal.", it: "Fai un respiro e riprova.", pt: "Respire fundo e tente de novo.", ru: "Сделай вдох и попробуй снова.", ar: "تنفس بعمق وحاول مرة أخرى.", zh: "深呼吸，再试一次。", hi: "एक गहरी सांस लें और फिर कोशिश करें।", ja: "一度落ち着いてもう一度挑戦しよう。", ko: "잠시 숨을 고르고 다시 시도해보세요." },
  retry: { en: "Try Again", tr: "Tekrar Dene", az: "Yenidən Cəhd Et", ka: "თავიდან სცადე", es: "Reintentar", fr: "Réessayer", de: "Erneut Versuchen", it: "Riprova", pt: "Tentar de Novo", ru: "Повторить", ar: "أعد المحاولة", zh: "重试", hi: "फिर कोशिश करें", ja: "リトライ", ko: "다시 시도" },
  display_name: { en: "Display Name", tr: "Görünen Adın", az: "Görünən Adın", ka: "შენი სახელი", es: "Tu Nombre", fr: "Ton Nom", de: "Dein Anzeigename", it: "Il Tuo Nome", pt: "Seu Nome", ru: "Твоё Имя", ar: "اسمك", zh: "你的昵称", hi: "आपका नाम", ja: "表示名", ko: "표시 이름" },
  name_hint: { en: "This name will be shown to friends on the daily challenge leaderboard.", tr: "Bu ad günlük görev sıralamasında arkadaşlarına gösterilecek.", az: "Bu ad günlük tapşırıq sıralamasında dostlarına göstəriləcək.", ka: "ეს სახელი მეგობრებს გამოუჩნდება დღის დავალების რეიტინგში.", es: "Este nombre se mostrará a tus amigos en el ranking del reto diario.", fr: "Ce nom sera affiché à tes amis dans le classement du défi du jour.", de: "Dieser Name wird Freunden in der Rangliste der täglichen Herausforderung angezeigt.", it: "Questo nome sarà mostrato agli amici nella classifica della sfida giornaliera.", pt: "Esse nome será mostrado aos amigos no ranking do desafio diário.", ru: "Это имя будет показано друзьям в рейтинге ежедневного задания.", ar: "سيظهر هذا الاسم لأصدقائك في ترتيب التحدي اليومي.", zh: "此昵称将显示在每日挑战排行榜上，供好友查看。", hi: "यह नाम दोस्तों को दैनिक चैलेंज रैंकिंग में दिखाई देगा।", ja: "この名前はデイリーチャレンジのランキングで友達に表示されます。", ko: "이 이름은 데일리 챌린지 순위에서 친구들에게 표시됩니다." },
  save: { en: "Save", tr: "Kaydet", az: "Saxla", ka: "შენახვა", es: "Guardar", fr: "Enregistrer", de: "Speichern", it: "Salva", pt: "Salvar", ru: "Сохранить", ar: "حفظ", zh: "保存", hi: "सेव करें", ja: "保存", ko: "저장" },
  daily_complete: { en: "Daily Challenge Complete!", tr: "Günlük Görev Tamamlandı!", az: "Günlük Tapşırıq Tamamlandı!", ka: "დღის დავალება დასრულდა!", es: "¡Reto Diario Completado!", fr: "Défi du Jour Terminé !", de: "Tägliche Herausforderung Geschafft!", it: "Sfida Giornaliera Completata!", pt: "Desafio Diário Concluído!", ru: "Ежедневное Задание Пройдено!", ar: "اكتمل التحدي اليومي!", zh: "每日挑战完成！", hi: "दैनिक चैलेंज पूरा हुआ!", ja: "デイリーチャレンジ完了！", ko: "데일리 챌린지 완료!" },
  daily_stats: { en: "Time: {time} • Hearts left: {hearts}", tr: "Süre: {time} • Kalan can: {hearts}", az: "Vaxt: {time} • Qalan can: {hearts}", ka: "დრო: {time} • დარჩენილი გული: {hearts}", es: "Tiempo: {time} • Corazones restantes: {hearts}", fr: "Temps : {time} • Cœurs restants : {hearts}", de: "Zeit: {time} • Verbleibende Leben: {hearts}", it: "Tempo: {time} • Vite rimaste: {hearts}", pt: "Tempo: {time} • Vidas restantes: {hearts}", ru: "Время: {time} • Осталось жизней: {hearts}", ar: "الوقت: {time} • القلوب المتبقية: {hearts}", zh: "用时：{time} • 剩余生命：{hearts}", hi: "समय: {time} • बची हुई जान: {hearts}", ja: "時間: {time} • 残りハート: {hearts}", ko: "시간: {time} • 남은 하트: {hearts}" },
  score_new_best: { en: "Score: {score} (new best!)", tr: "Skor: {score} (yeni en iyi!)", az: "Xal: {score} (yeni ən yaxşı!)", ka: "ქულა: {score} (ახალი რეკორდი!)", es: "Puntuación: {score} (¡nuevo récord!)", fr: "Score : {score} (nouveau record !)", de: "Punkte: {score} (neuer Bestwert!)", it: "Punteggio: {score} (nuovo record!)", pt: "Pontuação: {score} (novo recorde!)", ru: "Очки: {score} (новый рекорд!)", ar: "النتيجة: {score} (رقم قياسي جديد!)", zh: "得分：{score}（新纪录！）", hi: "स्कोर: {score} (नया बेस्ट!)", ja: "スコア: {score}（新記録！）", ko: "점수: {score} (신기록!)" },
  score_prev_best: { en: "Score: {score} (your best: {prev})", tr: "Skor: {score} (en iyin: {prev})", az: "Xal: {score} (ən yaxşın: {prev})", ka: "ქულა: {score} (შენი საუკეთესო: {prev})", es: "Puntuación: {score} (tu mejor: {prev})", fr: "Score : {score} (ton record : {prev})", de: "Punkte: {score} (dein Bestwert: {prev})", it: "Punteggio: {score} (il tuo record: {prev})", pt: "Pontuação: {score} (seu recorde: {prev})", ru: "Очки: {score} (твой рекорд: {prev})", ar: "النتيجة: {score} (أفضل نتيجة لك: {prev})", zh: "得分：{score}（你的最佳：{prev}）", hi: "स्कोर: {score} (आपका बेस्ट: {prev})", ja: "スコア: {score}（自己ベスト: {prev}）", ko: "점수: {score} (최고 점수: {prev})" },
  language: { en: "Language", tr: "Dil", az: "Dil", ka: "ენა", es: "Idioma", fr: "Langue", de: "Sprache", it: "Lingua", pt: "Idioma", ru: "Язык", ar: "اللغة", zh: "语言", hi: "भाषा", ja: "言語", ko: "언어" },

  ach_first_knot_title: { en: "First Knot", tr: "İlk Düğüm", az: "İlk Düyün", ka: "პირველი კვანძი", es: "Primer Nudo", fr: "Premier Nœud", de: "Erster Knoten", it: "Primo Nodo", pt: "Primeiro Nó", ru: "Первый Узел", ar: "العقدة الأولى", zh: "第一个结", hi: "पहली गांठ", ja: "最初の結び目", ko: "첫 매듭" },
  ach_first_knot_desc: { en: "Complete the first level", tr: "İlk seviyeyi tamamla", az: "İlk səviyyəni tamamla", ka: "დაასრულე პირველი დონე", es: "Completa el primer nivel", fr: "Termine le premier niveau", de: "Schließe das erste Level ab", it: "Completa il primo livello", pt: "Complete o primeiro nível", ru: "Пройди первый уровень", ar: "أكمل المستوى الأول", zh: "完成第一关", hi: "पहला लेवल पूरा करें", ja: "最初のレベルをクリア", ko: "첫 번째 레벨 완료" },
  ach_level10_title: { en: "Ten Levels", tr: "On Seviye", az: "On Səviyyə", ka: "ათი დონე", es: "Diez Niveles", fr: "Dix Niveaux", de: "Zehn Level", it: "Dieci Livelli", pt: "Dez Níveis", ru: "Десять Уровней", ar: "عشرة مستويات", zh: "十关达成", hi: "दस लेवल", ja: "10レベル達成", ko: "10레벨 달성" },
  ach_level10_desc: { en: "Reach level 11", tr: "11. seviyeye ulaş", az: "11-ci səviyyəyə çat", ka: "მიაღწიე 11 დონეს", es: "Llega al nivel 11", fr: "Atteins le niveau 11", de: "Erreiche Level 11", it: "Raggiungi il livello 11", pt: "Alcance o nível 11", ru: "Дойди до уровня 11", ar: "اصل إلى المستوى 11", zh: "到达第 11 关", hi: "लेवल 11 तक पहुंचें", ja: "レベル11に到達", ko: "레벨 11에 도달" },
  ach_level25_title: { en: "Quarter Way", tr: "Çeyrek Yol", az: "Dörddə Bir", ka: "მეოთხედი გზა", es: "Un Cuarto del Camino", fr: "Un Quart du Chemin", de: "Viertelweg", it: "Un Quarto di Strada", pt: "Um Quarto do Caminho", ru: "Четверть Пути", ar: "ربع الطريق", zh: "四分之一旅程", hi: "एक चौथाई रास्ता", ja: "四分の一の道", ko: "4분의 1 지점" },
  ach_level25_desc: { en: "Reach level 26", tr: "26. seviyeye ulaş", az: "26-cı səviyyəyə çat", ka: "მიაღწიე 26 დონეს", es: "Llega al nivel 26", fr: "Atteins le niveau 26", de: "Erreiche Level 26", it: "Raggiungi il livello 26", pt: "Alcance o nível 26", ru: "Дойди до уровня 26", ar: "اصل إلى المستوى 26", zh: "到达第 26 关", hi: "लेवल 26 तक पहुंचें", ja: "レベル26に到達", ko: "레벨 26에 도달" },
  ach_all_levels_title: { en: "Knot Master", tr: "Knot Ustası", az: "Düyün Ustası", ka: "კვანძების ოსტატი", es: "Maestro de Nudos", fr: "Maître des Nœuds", de: "Knotenmeister", it: "Maestro dei Nodi", pt: "Mestre dos Nós", ru: "Мастер Узлов", ar: "سيد العُقد", zh: "解结大师", hi: "नॉट मास्टर", ja: "ノットマスター", ko: "매듭 마스터" },
  ach_all_levels_desc: { en: "Complete all levels", tr: "Tüm seviyeleri tamamla", az: "Bütün səviyyələri tamamla", ka: "დაასრულე ყველა დონე", es: "Completa todos los niveles", fr: "Termine tous les niveaux", de: "Schließe alle Level ab", it: "Completa tutti i livelli", pt: "Complete todos os níveis", ru: "Пройди все уровни", ar: "أكمل جميع المستويات", zh: "完成所有关卡", hi: "सभी लेवल पूरे करें", ja: "すべてのレベルをクリア", ko: "모든 레벨 완료" },
  ach_perfect_title: { en: "Perfect Solve", tr: "Mükemmel Çözüm", az: "Mükəmməl Həll", ka: "უმაღლესი შედეგი", es: "Solución Perfecta", fr: "Solution Parfaite", de: "Perfekte Lösung", it: "Soluzione Perfetta", pt: "Solução Perfeita", ru: "Идеальное Решение", ar: "حل مثالي", zh: "完美通关", hi: "परफेक्ट सॉल्व", ja: "完璧な解答", ko: "완벽한 풀이" },
  ach_perfect_desc: { en: "Finish a level without losing a heart", tr: "Bir seviyeyi cansız kayıp yapmadan bitir", az: "Bir səviyyəni can itirmədən bitir", ka: "დაასრულე დონე გულის დაკარგვის გარეშე", es: "Termina un nivel sin perder corazones", fr: "Termine un niveau sans perdre de cœur", de: "Schließe ein Level ohne Lebensverlust ab", it: "Completa un livello senza perdere vite", pt: "Termine um nível sem perder vidas", ru: "Пройди уровень без потери жизней", ar: "أنهِ مستوى دون فقدان أي قلب", zh: "在不损失生命的情况下完成一关", hi: "बिना जान खोए एक लेवल पूरा करें", ja: "ハートを失わずにレベルをクリア", ko: "하트를 잃지 않고 레벨 완료" },
  ach_star_collector_title: { en: "Star Collector", tr: "Yıldız Koleksiyoncusu", az: "Ulduz Kolleksiyaçısı", ka: "ვარსკვლავების კოლექციონერი", es: "Coleccionista de Estrellas", fr: "Collectionneur d'Étoiles", de: "Sternensammler", it: "Collezionista di Stelle", pt: "Colecionador de Estrelas", ru: "Коллекционер Звёзд", ar: "جامع النجوم", zh: "星星收藏家", hi: "स्टार कलेक्टर", ja: "スターコレクター", ko: "별 수집가" },
  ach_star_collector_desc: { en: "Earn 3 stars on 10 levels", tr: "10 seviyede 3 yıldız kazan", az: "10 səviyyədə 3 ulduz qazan", ka: "მოაგროვე 3 ვარსკვლავი 10 დონეზე", es: "Consigue 3 estrellas en 10 niveles", fr: "Gagne 3 étoiles sur 10 niveaux", de: "Erreiche 3 Sterne in 10 Levels", it: "Ottieni 3 stelle in 10 livelli", pt: "Ganhe 3 estrelas em 10 níveis", ru: "Получи 3 звезды на 10 уровнях", ar: "احصل على 3 نجوم في 10 مستويات", zh: "在 10 个关卡中获得 3 星", hi: "10 लेवल में 3 स्टार पाएं", ja: "10レベルで3つ星を獲得", ko: "10개 레벨에서 별 3개 획득" },
  ach_daily_explorer_title: { en: "Daily Explorer", tr: "Günlük Kaşif", az: "Günlük Kəşfiyyatçı", ka: "დღის მკვლევარი", es: "Explorador Diario", fr: "Explorateur Quotidien", de: "Täglicher Entdecker", it: "Esploratore Giornaliero", pt: "Explorador Diário", ru: "Ежедневный Исследователь", ar: "مستكشف يومي", zh: "每日探索者", hi: "डेली एक्सप्लोरर", ja: "デイリー探検家", ko: "데일리 탐험가" },
  ach_daily_explorer_desc: { en: "Complete a daily challenge", tr: "Bir günlük görevi tamamla", az: "Bir günlük tapşırığı tamamla", ka: "დაასრულე ერთი დღის დავალება", es: "Completa un reto diario", fr: "Termine un défi du jour", de: "Schließe eine tägliche Herausforderung ab", it: "Completa una sfida giornaliera", pt: "Complete um desafio diário", ru: "Пройди ежедневное задание", ar: "أكمل تحديًا يوميًا", zh: "完成一次每日挑战", hi: "एक दैनिक चैलेंज पूरा करें", ja: "デイリーチャレンジをクリア", ko: "데일리 챌린지 완료" },

  tut1_title: { en: "Knot Escape", tr: "Knot Escape", az: "Knot Escape", ka: "Knot Escape", es: "Knot Escape", fr: "Knot Escape", de: "Knot Escape", it: "Knot Escape", pt: "Knot Escape", ru: "Knot Escape", ar: "Knot Escape", zh: "Knot Escape", hi: "Knot Escape", ja: "Knot Escape", ko: "Knot Escape" },
  tut1_text: { en: "The board is full of tangled ropes. Solve them all to clear the board completely.", tr: "Tahta birbirine dolanmış iplerle dolu. Hepsini çözüp tahtayı tamamen boşaltmalısın.", az: "Taxta bir-birinə dolaşmış iplərlə doludur. Hamısını həll edib taxtanı tamamilə boşalt.", ka: "დაფა სავსეა გადახლართული თოკებით. ყველა გადააჭერი და დაფა მთლიანად გაასუფთავე.", es: "El tablero está lleno de cuerdas enredadas. Resuélvelas todas para vaciarlo por completo.", fr: "Le plateau est rempli de cordes emmêlées. Résous-les toutes pour le vider complètement.", de: "Das Spielfeld ist voller verknoteter Seile. Löse sie alle, um das Feld komplett zu leeren.", it: "La griglia è piena di corde aggrovigliate. Risolvile tutte per svuotarla completamente.", pt: "O tabuleiro está cheio de cordas emaranhadas. Resolva todas para esvaziá-lo completamente.", ru: "Поле заполнено спутанными веревками. Распутай их все, чтобы полностью очистить поле.", ar: "اللوحة مليئة بالحبال المتشابكة. حلها جميعًا لتفريغ اللوحة بالكامل.", zh: "棋盘上布满了缠结的绳子。解开所有绳子，让棋盘完全清空。", hi: "बोर्ड उलझी हुई रस्सियों से भरा है। सबको सुलझाकर बोर्ड को पूरी तरह खाली करें।", ja: "ボードは絡まったロープでいっぱいです。すべて解いてボードを空にしましょう。", ko: "보드가 엉킨 줄로 가득합니다. 모두 풀어서 보드를 완전히 비워보세요." },
  tut2_title: { en: "Touch a Rope", tr: "İpe Dokun", az: "İpə Toxun", ka: "შეეხე თოკს", es: "Toca una Cuerda", fr: "Touche une Corde", de: "Tippe ein Seil An", it: "Tocca una Corda", pt: "Toque em uma Corda", ru: "Коснись Веревки", ar: "اضغط على حبل", zh: "点击绳子", hi: "रस्सी को छूएं", ja: "ロープをタップ", ko: "줄을 터치하세요" },
  tut2_text: { en: "An arrow slides in its direction if the path ahead is clear. You can tap anywhere on a rope.", tr: "Bir ipin oku, önündeki yol boşsa o yöne doğru kayıp gider. İpin herhangi bir yerine dokunabilirsin.", az: "Bir ipin ox işarəsi, önündəki yol boşdursa həmin istiqamətə sürüşür. İpin istənilən yerinə toxuna bilərsən.", ka: "თოკის ისარი იმ მიმართულებით დაიწევს, თუ წინ გზა თავისუფალია. შეხება შესაძლებელია თოკის ნებისმიერ წერტილზე.", es: "Una flecha se desliza en su dirección si el camino está libre. Puedes tocar cualquier parte de la cuerda.", fr: "Une flèche glisse dans sa direction si le chemin est libre. Tu peux toucher n'importe où sur la corde.", de: "Ein Pfeil rutscht in seine Richtung, wenn der Weg frei ist. Du kannst überall auf das Seil tippen.", it: "Una freccia scorre nella sua direzione se il percorso è libero. Puoi toccare qualsiasi punto della corda.", pt: "Uma seta deslizará na sua direção se o caminho estiver livre. Você pode tocar em qualquer ponto da corda.", ru: "Стрелка скользит в своём направлении, если путь свободен. Можно коснуться любой точки веревки.", ar: "ينزلق السهم في اتجاهه إذا كان الطريق أمامه فاضيًا. يمكنك الضغط على أي نقطة من الحبل.", zh: "如果箭头前方道路畅通，绳子就会朝箭头方向滑出。可以点击绳子的任意位置。", hi: "यदि आगे का रास्ता खाली है, तो रस्सी का एरो उस दिशा में सरक जाएगा। रस्सी पर कहीं भी टैप करें।", ja: "前方の道が空いていれば、矢印はその方向にスライドします。ロープのどこをタップしてもOKです。", ko: "앞쪽 길이 비어 있으면 화살표가 그 방향으로 이동합니다. 줄의 어느 부분이든 탭할 수 있습니다." },
  tut3_title: { en: "Watch the Order", tr: "Sıraya Dikkat", az: "Ardıcıllığa Diqqət", ka: "მიაქციე ყურადღება რიგს", es: "Cuida el Orden", fr: "Attention à l'Ordre", de: "Achte auf die Reihenfolge", it: "Attento all'Ordine", pt: "Cuide da Ordem", ru: "Следи за Порядком", ar: "انتبه للترتيب", zh: "注意顺序", hi: "क्रम का ध्यान रखें", ja: "順番に注意", ko: "순서에 주의하세요" },
  tut3_text: { en: "If a rope's path is blocked by others, you'll lose a heart. Try to find the right order!", tr: "Önü başka iplerle kapalı bir ipe dokunursan bir can kaybedersin. Doğru çözüm sırasını bulmaya çalış!", az: "Önü başqa iplərlə bağlı olan bir ipə toxunsan, bir can itirəcəksən. Doğru həll ardıcıllığını tapmağa çalış!", ka: "თუ თოკის გზა სხვა თოკებითაა დაკეტილი და მას შეეხები, დაკარგავ ერთ გულს. სცადე იპოვო სწორი თანმიმდევრობა!", es: "Si el camino de una cuerda está bloqueado por otras y la tocas, perderás un corazón. ¡Encuentra el orden correcto!", fr: "Si le chemin d'une corde est bloqué par d'autres et que tu la touches, tu perds un cœur. Trouve le bon ordre !", de: "Wenn der Weg eines Seils von anderen blockiert ist und du es antippst, verlierst du ein Leben. Finde die richtige Reihenfolge!", it: "Se il percorso di una corda è bloccato da altre e la tocchi, perderai una vita. Trova l'ordine giusto!", pt: "Se o caminho de uma corda estiver bloqueado por outras e você tocá-la, perderá uma vida. Encontre a ordem certa!", ru: "Если путь веревки заблокирован другими и ты коснёшься её, потеряешь жизнь. Найди правильный порядок!", ar: "إذا كان طريق الحبل مسدودًا بحبال أخرى وضغطت عليه، ستفقد قلبًا. حاول إيجاد الترتيب الصحيح!", zh: "如果一条绳子的路径被其他绳子挡住，点击它会让你失去一颗心。试着找出正确的顺序！", hi: "अगर किसी रस्सी का रास्ता दूसरी रस्सियों से बंद है और आप उसे छूते हैं, तो आपकी एक जान चली जाएगी। सही क्रम खोजने की कोशिश करें!", ja: "他のロープに道を塞がれているロープをタップするとハートを1つ失います。正しい順番を見つけましょう！", ko: "다른 줄로 막혀 있는 줄을 터치하면 하트를 잃습니다. 올바른 순서를 찾아보세요!" },
  tut4_title: { en: "Helpers Available", tr: "Yardımcıların Var", az: "Köməkçilərin Var", ka: "გყავს დამხმარეები", es: "Tienes Ayuda", fr: "Tu as de l'Aide", de: "Du Hast Hilfe", it: "Hai degli Aiuti", pt: "Você Tem Ajuda", ru: "У Тебя Есть Помощники", ar: "لديك مساعدون", zh: "善用帮助", hi: "आपके पास मदद है", ja: "頼れるヘルパー", ko: "도움 기능이 있어요" },
  tut4_text: { en: "If you're stuck, Hint highlights a safe move, and Undo reverts your last move.", tr: "Sıkışırsan İpucu güvenli bir hamleyi parlatır, Geri Al ise son hamleni geri alır.", az: "Sıxılsan, İpucu təhlükəsiz bir hərəkəti işıqlandırır, Geri Al isə son hərəkətini geri qaytarır.", ka: "თუ გაიჭედები, მინიშნება გაჩვენებს უსაფრთხო სვლას, ხოლო გაუქმება დააბრუნებს ბოლო სვლას.", es: "Si te atascas, Pista resalta un movimiento seguro y Deshacer revierte tu última jugada.", fr: "Si tu es bloqué, Indice met en évidence un coup sûr, et Annuler revient sur ton dernier coup.", de: "Wenn du nicht weiterkommst, zeigt Hinweis einen sicheren Zug, und Rückgängig macht deinen letzten Zug rückgängig.", it: "Se sei bloccato, Suggerimento illumina una mossa sicura, e Annulla ripristina la tua ultima mossa.", pt: "Se ficar travado, Dica destaca um movimento seguro, e Desfazer reverte sua última jogada.", ru: "Если застрял, Подсказка выделит безопасный ход, а Отменить вернёт твой последний ход.", ar: "إذا توقفت، يضيء التلميح حركة آمنة، والتراجع يلغي حركتك الأخيرة.", zh: "卡住时，提示会高亮一个安全的移动，撤销可以撤回你上一步的操作。", hi: "अटक जाएं तो हिंट एक सुरक्षित चाल दिखाता है, और अनडू आपकी पिछली चाल वापस कर देता है।", ja: "詰まったら「ヒント」が安全な手を光らせ、「元に戻す」で直前の操作を取り消せます。", ko: "막혔다면 힌트가 안전한 수를 알려주고, 되돌리기로 마지막 수를 취소할 수 있습니다." },
};

const I18N = {};
for (const key in I18N_KEYS) {
  for (const lang in I18N_KEYS[key]) {
    (I18N[lang] = I18N[lang] || {})[key] = I18N_KEYS[key][lang];
  }
}

const LANG_KEY = "knot-escape-lang";

function detectLang() {
  const saved = localStorage.getItem(LANG_KEY);
  if (saved && I18N[saved]) return saved;
  const nav = ((navigator.language || "en").split("-")[0] || "en").toLowerCase();
  return I18N[nav] ? nav : "en";
}

let currentLang = detectLang();

function getLang() {
  return currentLang;
}

function setLang(code) {
  if (!I18N[code]) return;
  currentLang = code;
  localStorage.setItem(LANG_KEY, code);
  document.documentElement.lang = code;
}

function t(key, vars) {
  let str = (I18N[currentLang] && I18N[currentLang][key]) || I18N.en[key] || key;
  if (vars) {
    for (const k in vars) str = str.replace(new RegExp("\\{" + k + "\\}", "g"), vars[k]);
  }
  return str;
}

function applyStaticTranslations() {
  document.querySelectorAll("[data-i18n]").forEach((node) => {
    node.textContent = t(node.getAttribute("data-i18n"));
  });
  document.querySelectorAll("[data-i18n-placeholder]").forEach((node) => {
    node.placeholder = t(node.getAttribute("data-i18n-placeholder"));
  });
  document.documentElement.lang = currentLang;
}
